program: model_train.ipynb
method: bayes
metric:
  name: val_f1_micro
  goal: maximize
parameters:
  model_name:
    values: ["convnextv2_nano", "convnextv2_tiny"]
  learning_rate:
    distribution: log_uniform_values
    min: 1e-6
    max: 1e-3
  batch_size:
    values: [32, 64, 128]
  img_size:
    values: [224, 384]
  # Class imbalance handling
  class_weight_method:
    values: ["inverse_freq", "balanced", "sqrt_inverse_freq", "none"]
  loss_type:
    values: ["focal", "asymmetric", "weighted_bce"]
  epochs:
    value: 6  # Fixed for sweep
  use_wandb:
    value: true  # Always use wandb for sweeps
  wandb_project:
    value: "fn-content-classifier"
  wandb_entity:
    value: "miloszbertman"  # Set to your wandb username/team
  wandb_tags:
    value: ["sweep", "multilabel", "convnextv2"]
