program: model_train.ipynb
method: bayes
metric:
  name: best_pr_auc_macro
  goal: maximize
early_terminate:
  type: hyperband
  min_iter: 3     # check after epoch 3
  max_iter: 15    # your full number of epochs
  eta: 2          # kill ~50% of weak configs
  strict: true    # allow aggressive termination
parameters:
  # model_name:
  #   values: [ "convnextv2_nano", "convnextv2_tiny" ]
  bce_power:
    distribution: uniform
    min: 0.0
    max: 1.0
  tau_logit_adjust:
    distribution: uniform
    min: 0.0
    max: 1.0
  weight_decay:
    distribution: uniform
    min: 0.0
    max: 1.0